_target_: vp2.models.ivideogpt_interface.iVideoGPTPredictor

config_name: null
seed: null
vqgan_type: ctx_vqgan
pretrained_vqgan_name_or_path: null
pretrained_transformer_path: null
action_dim: 5
generate_max_batchsize: 100
decode_max_batchsize: 67
action_recon: False
lora: False
lora_r: 8
lora_alpha: 32
lora_dropout: 0.0
epoch: null

